(deffacts facts-phalacrocorax
	(M high)
	(T 4) CF 0.8
	(D high)
	(S medium)
	(length 215)
    (calamus (color grey))
    (calamus (color yellow))
    (vane-inner (color black))
    (vane-inner (color brown))
    (vane-outer (color black))
    (vane-outer (color brown))
    (vanes-upper (color black))
    (vanes-upper (color brown))
    (rachis-lower (color black))
    (rachis-upper (color black))
)
